name: mplsoccer-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - scipy
  - seaborn
  - sphinx
  - pyarrow
  - beautifulsoup4
  - lxml
  - selenium
  - python-chromedriver-binary
  - conda-forge::ffmpeg
  - pillow
  - pip
  - pip:
      - setuptools
      - twine
      - wheel
      - sphinx-gallery
      - sphinx_rtd_theme
      - numpydoc
      - -e .
