name: mplsoccer-docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - pandas
  - scipy
  - seaborn
  - jupyter
  - sphinx
  - pyarrow
  - beautifulsoup4
  - lxml
  - selenium
  - geckodriver
  - firefox
  - conda-forge::ffmpeg
  - pillow
  - pip
  - pip:
      - sphinx-gallery >= 0.7
      - sphinx_rtd_theme
      - numpydoc
      - -e .
